# Generated by Django 4.2.16 on 2026-03-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("judge", "0195_contest_delay_contest_alter_contest_forbidden_leave"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="version_update",
            field=models.PositiveIntegerField(default=0, verbose_name="update version"),
        ),
    ]
