# Generated by Django 4.2.16 on 2026-03-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("judge", "0196_submission_version_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="version_update",
            field=models.PositiveIntegerField(default=0, verbose_name="update version"),
        ),
        migrations.AddField(
            model_name="problem",
            name="version_update",
            field=models.PositiveIntegerField(default=0, verbose_name="update version"),
        ),
    ]
