# Generated by Django 4.2.29 on 2026-03-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("judge", "0198_problem_threshold_user_count_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="log",
            options={"ordering": ("-time",), "verbose_name": "logging", "verbose_name_plural": "logs"},
        ),
        migrations.AddField(
            model_name="contest",
            name="is_exam_contest",
            field=models.BooleanField(default=False, verbose_name="Exam contest"),
        ),
    ]
