# Generated by Django 4.2.29 on 2026-03-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("judge", "0199_alter_log_options_contest_is_exam_contest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contest",
            name="is_exam_contest",
            field=models.BooleanField(
                default=False,
                help_text="If true, the contest will be used for exam clients, and will have some special restrictions.",
                verbose_name="Exam contest",
            ),
        ),
    ]
