# Generated by Django 4.2.30 on 2026-04-24 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0201_rename_contestproblem_limit_point_to_limit_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestproblem',
            name='limit_problem',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='limit problem'),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên học sinh đạt thành tích', max_length=255)),
                ('award', models.CharField(help_text='Tên giải thưởng đạt được', max_length=255)),
                ('contest', models.CharField(help_text='Tên cuộc thi', max_length=255)),
                ('level', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('high', 'High School')], help_text='Cấp độ học sinh', max_length=255)),
                ('rank', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze'), ('special', 'Special')], default='special', help_text='Hạng thành tích', max_length=255)),
                ('featured', models.BooleanField(default=False, help_text='Hiển thị trên trang chủ')),
                ('year', models.ForeignKey(help_text='Năm học', null=True, on_delete=django.db.models.deletion.SET_NULL, to='judge.schoolyear')),
            ],
        ),
    ]
