# Generated by Django 4.2.30 on 2026-04-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0202_alter_contestproblem_limit_problem_achievement"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="avatar",
            field=models.ImageField(blank=True, help_text="Ảnh đại diện", null=True, upload_to="achievement/avatars/"),
        ),
    ]
