# Generated by Codex on 2026-05-22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("judge", "0203_achievement_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metadata",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(db_index=True, max_length=255, unique=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "metadata",
                "verbose_name_plural": "metadata",
            },
        ),
    ]
