# Generated by Django 4.2.30 on 2026-08-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0204_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
