[program:celery]
command=/home/ubuntu/tmath/.venv/bin/celery -A tmath worker
directory=/home/ubuntu/tmath/
# You should create a dedicated user for celery to run under.
user=ubuntu
group=ubuntu
stdout_logfile=/home/ubuntu/tmath/tmpdata/logs/celery.stdout.log
stderr_logfile=/home/ubuntu/tmath/tmpdata/logs/celery.stderr.log

