[program:site]
command=/home/ubuntu/tmath/.venv/bin/uwsgi --ini uwsgi.ini
directory=/home/ubuntu/tmath/
stopsignal=QUIT
stdout_logfile=/home/ubuntu/tmath/tmpdata/logs/site.stdout.log
stderr_logfile=/home/ubuntu/tmath/tmpdata/logs/site.stderr.log
